### PR TITLE
Improvement/log after having sent message

### PR DESCRIPTION
**Pull request by ankovi**
Little improvement related to logging after having sent the message to Rules instead of before...

### CODE REVIEW

**Review by gregoryrinaldi — APPROVED** [review]
ok

**Review by stainii — CHANGES_REQUESTED** [review]
- In what way is it better to log after (a possible failing) send to Rules, instead of before?
- passing variables over methods via a private variable is a dangerous idea in a stateless bean. It's up to the server if beans gets re-used.

**Review by gregoryrinaldi — CHANGES_REQUESTED** [review]
ok then we can revert I guess if it was better before for me is ok

**Comment by ankovi** [comment]
@stainii 

1) In what way is it better to log after (a possible failing) send to Rules, instead of before?
   - Well it is pretty clear... While it has already sent it to Rules, while rules validates it in almost the same 
      moment in parallel it is being logged in exchange... so you gain some milliseconds there, because of 
      this introduced parallelism... I fthe underlying ActiveMQ has problems then you wouldn't probably be 
     able to get even until here right?

2) passing variables over methods via a private variable is a dangerous idea in a stateless bean. It's up to the server if beans gets re-used.
   - Each time a message comes the method produceNewUUID(); is called and as a matter of fact the 
     UUID will always be good.. so even if the bean gets re-used the problem doesn't persist!
     This because when an EJB gets reused it means that it has already finished the previous executiuon.

**Comment by stainii** [comment]
1. Ok, so you gain miliseconds, at the cost of more (relatively) more complex code and the chance that there will be no log in exchange because the forwarding to Rules went wrong.
2. In the current implementation, each method does call the produceNewUUID(). This is not enforced in any way for future implementations. An unaware developer can cause some serious bugs. What's the reason you need to work with private attributes?

**Comment by ankovi** [comment]
1) Ok, so you gain miliseconds, at the cost of more (relatively) more complex code and the chance that there will be no log in exchange because the forwarding to Rules went wrong.
   - Well, complexity doesn't really rise I'd say, it is just one new field... Related to "the chance that there 
     will be no log in exchange because the forwarding to Rules went wrong." as I told in the previous if 
     you have ActiveMQ problems (The broker) then you will have issues anywhere, and probably the 
     message wouldn't even get here from the plugin.

In the current implementation, each method does call the produceNewUUID(). This is not enforced in any way for future implementations. An unaware developer can cause some serious bugs. What's the reason you need to work with private attributes?
    - This actually cannot be enforced without som relatively "big" changes..

**Comment by ankovi** [comment]
Related to this : "What's the reason you need to work with private attributes?" it can actually be avoided...

**Comment by stainii** [comment]
If this code would not introduce a private variable in a Stateless EJB, it would be in a better place.

**Comment by gregoryrinaldi** [comment]
Indeed no state can be stored on a stateless session bean

they should receive information by
1) injection
2) method params

In your case it should be in the scope of each method.
Thus personally I prefer the PrePersist method seems more coherent ...
Persist guid and then use guid
I guess at this stage of the project we have more critical things to do so maybe keep that branch for later

**Comment by ankovi** [comment]
Already changed the private variable..
For the rest we don't merge it now, maybe later when we have less pressing matters..

**Pull request closed without merging**
