### PR TITLE
GitHub Synchronization with the latest from DG-MARE

### PR DESCRIPTION
**Pull request by gkgeorgiev**

### CODE REVIEW

**Comment by Ozsie** [comment]
test this please

**Review by Ozsie — CHANGES_REQUESTED** [review]
There is a constant missing in ExchangeModelConstants, or at least it's there with the wrong name.

Maybe ACTIVITY_EVENT_QUEUE should be replaced by ACTIVITY_RESPONSE_QUEUE?

Also, there is some sort of problem with Topic and Queue

[ERROR] /var/lib/jenkins/workspace/UVMS-Exchange-APP-Pull-Request/message/src/main/java/eu/europa/ec/fisheries/uvms/exchange/message/producer/bean/MessageProducerBean.java:[79,73] cannot find symbol
[ERROR] symbol:   variable ACTIVITY_EVENT_QUEUE
[ERROR] location: class eu.europa.ec.fisheries.uvms.exchange.model.constant.ExchangeModelConstants
[ERROR] /var/lib/jenkins/workspace/UVMS-Exchange-APP-Pull-Request/message/src/main/java/eu/europa/ec/fisheries/uvms/exchange/message/producer/bean/MessageProducerBean.java:[80,40] incompatible types: javax.jms.Topic cannot be converted to javax.jms.Queue

**Comment by Ozsie** [comment]
test this please

**Comment by gkgeorgiev** [comment]
I'm fixing it right now, thx

**Comment by Ozsie** [comment]
@gkgeorgiev Sorry, the comment was not directed at you. If you comment the pull request with "test this please" Jenkins starts a new build.

**Comment by Ozsie** [comment]
test this please

**Comment by gkgeorgiev** [comment]
@Ozsie , now Jenkins compiles the pull request ... please review it again, thx!

**Review by Ozsie — APPROVED** [review]
All good

**Pull request merged**
