### PR TITLE
Bel dev

### PR DESCRIPTION
**Pull request by stainii**
Make it possible to receive and send FLUX messages for the Sales module.

### CODE REVIEW

**Comment by ghost** [comment]
test me

**Comment by stainii** [comment]
The build was succesful, but fails again because the Exchange-model that was installed in the Jenkins' local Maven repo contains a bru-dev snapshot instead of the bel-dev snapshot.

Can we finish the pull requests on Exchange-model first, before going further with this one?

**Comment by ebrygg** [comment]
please test me

**Comment by ebrygg** [comment]
please test me

**Comment by ebrygg** [comment]
please test me

**Comment by stainii** [comment]
Please test me

**Pull request merged**
